version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: true
    TF_INPUT: 0
    TF_VAR_owner_email: pttp@justice.gov.uk
    TF_VAR_enable_critical_notifications: true
    TF_VAR_enable_cloudtrail_log_shipping_to_cloudwatch: true
    TF_VAR_enable_shared_services_log_destination: true
    TF_VAR_enable_transit_gateway_attachment: true
    TF_VAR_enable_api_gateway_custom_domain: true
    TF_VAR_enable_api_gateway_logs: true
    TF_VAR_env: ${ENV}
  parameter-store:
    TF_VAR_enable_peering:                   "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/enable_peering"
    TF_VAR_assume_role:                      "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"
    TF_VAR_logging_cidr_block:               "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/logging_cidr_block"
    TF_VAR_syslog_receiver_cidr_block:       "/staff-device/$ENV/syslog_receiver_cidr_block"
    TF_VAR_ost_vpc_id:                       "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/ost_vpc_id"
    TF_VAR_ost_aws_account_id:               "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/ost_aws_account_id"
    TF_VAR_vpn_hosted_zone_id:               "/codebuild/$ENV/vpn_hosted_zone_id"
    TF_VAR_ost_vpc_cidr_block:               "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/ost_vpc_cidr_block"
    TF_VAR_ost_username:                     "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/ost_username"
    TF_VAR_ost_password:                     "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/ost_password"
    TF_VAR_ost_url:                          "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/ost_url"
    TF_VAR_critical_notification_recipients: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/critical_notification_recipients"
    TF_VAR_api_gateway_custom_domain:        "/staff-device/$ENV/logging/api_gateway_domain_name"
    # function beats related config
    ROLE_ARN:                                "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"
    OST_KEY:                                 "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/moj.key"
    OST_CRT:                                 "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/moj.crt"
    OST_CA_CRT:                              "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/elk-ca.crt"
    TF_VAR_syslog_load_balancer_private_ip_eu_west_2a: "/staff-device/syslog/$ENV/load_balancer_private_ip_eu_west_2a"
    TF_VAR_syslog_load_balancer_private_ip_eu_west_2b: "/staff-device/syslog/$ENV/load_balancer_private_ip_eu_west_2b"
    TF_VAR_syslog_load_balancer_private_ip_eu_west_2c: "/staff-device/syslog/$ENV/load_balancer_private_ip_eu_west_2c"
    TF_VAR_transit_gateway_id:                "/staff-device/dhcp/$ENV/transit_gateway_id"
    TF_VAR_transit_gateway_route_table_id:    "/staff-device/dhcp/$ENV/transit_gateway_route_table_id"

phases:
  install:
    commands:
      - wget --no-verbose -O terraform.zip https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin
      - wget --no-verbose -O functionbeat.tar.gz https://artifacts.elastic.co/downloads/beats/functionbeat/functionbeat-7.7.0-linux-x86_64.tar.gz
      - tar -xzf functionbeat.tar.gz
      - mv functionbeat-*-linux-x86_64 functionbeat

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      # terraform deploy
      - terraform init -no-color --backend-config="key=terraform.$ENV.state" -reconfigure -upgrade
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - terraform init -no-color --backend-config="key=terraform.$ENV.state"
      - terraform apply --auto-approve -no-color
      - ./scripts/publish_terraform_outputs
      # create temporay role
      - TEMP_ROLE=`aws sts assume-role --role-arn $ROLE_ARN --role-session-name ci-build-$CODEBUILD_BUILD_NUMBER`
      - echo $TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      # build lambdas
      - cd functionbeat
      - echo $OST_KEY    | base64 -d > moj.key
      - echo $OST_CRT    | base64 -d > moj.crt
      - echo $OST_CA_CRT | base64 -d > elk-ca.crt
      - ./functionbeat -e -c ../functionbeat-config.yml test config
      - ./functionbeat -e -c ../functionbeat-config.yml package
      - zip -u package-aws.zip moj.crt moj.key elk-ca.crt
      # build templates
      - ./functionbeat -e -c ../functionbeat-config.yml export function staff-device-$ENV-infra-cloudwatch-syslog > cf-$ENV-cloudwatch-syslog.json
      - ./functionbeat -e -c ../functionbeat-config.yml export function staff-device-$ENV-infra-cloudwatch > cf-$ENV-cloudwatch.json
      - ./functionbeat -e -c ../functionbeat-config.yml export function staff-device-$ENV-infra-sqs        > cf-$ENV-sqs.json
      - ./functionbeat -e -c ../functionbeat-config.yml export function staff-device-$ENV-infra-kinesis    > cf-$ENV-kinesis.json

      # upload lambdas
      - export CW_SYSLOG_S3_KEY=`cat cf-$ENV-cloudwatch-syslog.json | jq -r '.. |."S3Key"? | select(. != null)'`
      - export CW_S3_KEY=`cat cf-$ENV-cloudwatch.json | jq -r '.. |."S3Key"? | select(. != null)'`
      - export SQS_S3_KEY=`cat cf-$ENV-sqs.json       | jq -r '.. |."S3Key"? | select(. != null)'`
      - export KINESIS_S3_KEY=`cat cf-$ENV-kinesis.json | jq -r '.. |."S3Key"? | select(. != null)'`
      - aws s3 cp --no-progress ./package-aws.zip s3://staff-device-$ENV-infra-functionbeat-artifacts/$CW_SYSLOG_S3_KEY
      - aws s3 cp --no-progress ./package-aws.zip s3://staff-device-$ENV-infra-functionbeat-artifacts/$CW_S3_KEY
      - aws s3 cp --no-progress ./package-aws.zip s3://staff-device-$ENV-infra-functionbeat-artifacts/$SQS_S3_KEY
      - aws s3 cp --no-progress ./package-aws.zip s3://staff-device-$ENV-infra-functionbeat-artifacts/$KINESIS_S3_KEY
      # upload templates
      - |
        aws cloudformation deploy \
          --stack-name staff-device-$ENV-infra-cloudwatch-syslog \
          --template-file ./cf-$ENV-cloudwatch-syslog.json \
          --no-fail-on-empty-changeset
      - |
        aws cloudformation deploy \
          --stack-name staff-device-$ENV-infra-cloudwatch \
          --template-file ./cf-$ENV-cloudwatch.json \
          --no-fail-on-empty-changeset
      - |
        aws cloudformation deploy \
          --stack-name staff-device-$ENV-infra-sqs \
          --template-file ./cf-$ENV-sqs.json \
          --no-fail-on-empty-changeset
      - |
        aws cloudformation deploy \
          --stack-name staff-device-$ENV-infra-kinesis \
          --template-file ./cf-$ENV-kinesis.json \
          --no-fail-on-empty-changeset

      # ensure log retention period is set for all CloudWatch logs
      - cd -
      - ./scripts/ensure_cloudwatch_log_retention_policies.sh
