#!/bin/bash

cd bootstrap

export AWS_PROFILE="pttp-$1"
#export TF_LOG=debug
export TF_IN_AUTOMATION=true
AWS_PROFILE="pttp-$1" terraform init --reconfigure
AWS_PROFILE="pttp-$1" terraform workspace new "pttp-pre-production"
AWS_PROFILE="pttp-$1" terraform workspace new "pttp-development"
AWS_PROFILE="pttp-$1" terraform workspace new "pttp-production"
AWS_PROFILE="pttp-$1" terraform workspace select "pttp-$1"
AWS_PROFILE="pttp-$1" terraform init
AWS_PROFILE="pttp-$1" terraform apply

cd -