#!/bin/bash

set -e -o pipefail

deploy_functionbeat() {
  name=$1

  ./functionbeat -e -c ../functionbeat-config.yml export function staff-device-$ENV-infra-${name} > cf-$ENV-${name}.json
  key=`cat cf-$ENV-${name}.json | jq -r '.. |."S3Key"? | select(. != null)'`
  aws s3 cp --no-progress ./package-aws.zip s3://staff-device-$ENV-infra-functionbeat-artifacts/${key}

  aws cloudformation deploy \
    --stack-name staff-device-$ENV-infra-${name} \
    --template-file ./cf-$ENV-${name}.json \
    --no-fail-on-empty-changeset
}

cd functionbeat
echo $OST_KEY    | base64 -d > moj.key
echo $OST_CRT    | base64 -d > moj.crt
echo $OST_CA_CRT | base64 -d > elk-ca.crt

./functionbeat -e -c ../functionbeat-config.yml test config
./functionbeat -e -c ../functionbeat-config.yml package
zip -u package-aws.zip moj.crt moj.key elk-ca.crt

deploy_functionbeat "cloudwatch-syslog"
deploy_functionbeat "cloudwatch"
deploy_functionbeat "sqs"
deploy_functionbeat "kinesis"

if [[ ! -z $TFVAR_enable_dlq ]]; then
  deploy_functionbeat "dlq"
fi
