#!/bin/bash

set -e -u -o pipefail

wget --no-verbose -O functionbeat.tar.gz https://artifacts.elastic.co/downloads/beats/functionbeat/functionbeat-7.7.0-linux-x86_64.tar.gz
tar -xzf functionbeat.tar.gz
mv functionbeat-*-linux-x86_64 functionbeat
